name: "The name of your action here"
description: "Provide a description here"
author: "Your name or organization here"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  github-token:
    description: "The GitHub token to use"
    default: ${{ github.token }}
  close_count:
    description: "The number of issues to close"
    default: "5"

runs:
  using: node20
  main: dist/index.js
